// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/shows/[slug]/index.ts";
import * as $3 from "./routes/api/shows/[slug]/soundcloud.ts";
import * as $4 from "./routes/api/shows/index.ts";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/tracklists/[slug]/index.tsx";
import * as $7 from "./routes/tracklists/index.tsx";
import * as $8 from "./routes/tracklists/t/[tag].tsx";
import * as $$0 from "./islands/MusicRoutes.tsx";
import * as $$1 from "./islands/PlayerWidget.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/shows/[slug]/index.ts": $2,
    "./routes/api/shows/[slug]/soundcloud.ts": $3,
    "./routes/api/shows/index.ts": $4,
    "./routes/index.tsx": $5,
    "./routes/tracklists/[slug]/index.tsx": $6,
    "./routes/tracklists/index.tsx": $7,
    "./routes/tracklists/t/[tag].tsx": $8,
  },
  islands: {
    "./islands/MusicRoutes.tsx": $$0,
    "./islands/PlayerWidget.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
