// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_shows_slug_soundcloud from "./routes/api/shows/[slug]/soundcloud.ts";
import * as $index from "./routes/index.tsx";
import * as $tracklists_slug_index from "./routes/tracklists/[slug]/index.tsx";
import * as $tracklists_index from "./routes/tracklists/index.tsx";
import * as $tracklists_t_tag_ from "./routes/tracklists/t/[tag].tsx";
import * as $tracks_id_ from "./routes/tracks/[id].tsx";
import * as $PlayShow from "./islands/PlayShow.tsx";
import * as $PlayerWidget from "./islands/PlayerWidget.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/shows/[slug]/soundcloud.ts": $api_shows_slug_soundcloud,
    "./routes/index.tsx": $index,
    "./routes/tracklists/[slug]/index.tsx": $tracklists_slug_index,
    "./routes/tracklists/index.tsx": $tracklists_index,
    "./routes/tracklists/t/[tag].tsx": $tracklists_t_tag_,
    "./routes/tracks/[id].tsx": $tracks_id_,
  },
  islands: {
    "./islands/PlayShow.tsx": $PlayShow,
    "./islands/PlayerWidget.tsx": $PlayerWidget,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
