name: live

on: [deployment_status]

jobs:
  lighthouse:
    name: lighthouse
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success' && github.event.deployment_status.creator.login == 'deno-deploy[bot]'

    env:
      URL: ${{ github.event.deployment_status.environment_url }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        name: Install Node.js 16.x
        with:
          node-version: 16.x

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.9.x

      - name: Run Lighthouse
        run: lhci autorun --collect.url="$URL" --collect.url="$URL/docs/introduction" --upload.target="temporary-public-storage"
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
